### ISSUE TITLE
Got strange result from the example_script with ADL_LRS

### ISSUE THREAD

**Issue by gtoffoli** [RusticiSoftware/TinCanPython#97]
I've just installed the reference implementation of the LRS at https://github.com/adlnet/ADL_LRS.
Then I've tried to access it from a Python shell using this TinCanPython library and the code of the example_script.
As I'm explaining below, I was puzzled by inconsistent results.

The script goes in error when trying to retrieve the statement:

    Now, retrieving statement...
    Traceback (most recent call last):
      File "<console>", line 1, in <module>
      File "...\example_script.py", line 88, in <module>
        response = lrs.retrieve_statement(response.content.id)
    AttributeError: 'NoneType' object has no attribute 'id'

If I inspect the response object just after save_statement, I get

    >>> response
    <tincan.lrs_response.LRSResponse object at 0x04AC95F0>
    >>> response.success
    False
    >>> response.response.status
    500
    >>> response.data
    u'[Errno 111] Connection refused'

However,

1. By accessing the LRS from its web interface (Django application), I see that the statement has been correctly recorded.
2. I am also able to retrieve the statement, by executing the subsequent code of the example_script and putting as argument the literal id taken from said interface in place of the expression _response.content.id_

**Comment by gtoffoli** [comment]
I've repeated the test, with success, using an "Explore plan" on Vax LRS.
Thus the problem seems to lie within the ADL_LRS implementation or in the configuration I did of it.
